openapi: 3.0.0
info:
  title: Social App
  description: My First backend application
  version: v1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: localhost version 1
  - url: https://localhost:3000/api/v1
    description: with https protocol.

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer